# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('loan', models.CharField(max_length=200, verbose_name='\u8d37\u6b3eid')),
                ('jhj_mobile', models.CharField(max_length=11, verbose_name='\u6295\u8d44\u4eba\u624b\u673a\u53f7')),
                ('nm_mobile', models.CharField(max_length=11, verbose_name='\u501f\u6b3e\u4eba\u624b\u673a\u53f7')),
                ('period', models.IntegerField(max_length=2, verbose_name='\u8fd8\u6b3e\u671f\u6570')),
                ('loanType', models.IntegerField(max_length=1, verbose_name='\u8fd8\u6b3e\u7c7b\u578b,1\u662f\u667a\u6167\u6295,2\u662f\u76f4\u6295')),
                ('rate', models.CharField(max_length=200, verbose_name='\u76f4\u6295\u7684\u603b\u5229\u7387')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentFront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaymentType', models.CharField(max_length=200, verbose_name='\u8fd8\u6b3e\u7c7b\u578b,1\u6b63\u5e38\u8fd8\u6b3e,2\u62c5\u4fdd\u4ee3\u507f,3\u903e\u671f\u8fd8\u6b3e')),
                ('jhj_xw_front', models.CharField(max_length=200, verbose_name='jhj\u65b0\u7f51\u91d1\u989d')),
                ('nm_xw_front', models.CharField(max_length=200, verbose_name='\u5357\u95e8\u65b0\u7f51\u91d1\u989d')),
                ('guarantee_xw_front', models.CharField(max_length=200, verbose_name='\u62c5\u4fdd\u65b0\u7f51\u91d1\u989d')),
                ('income_xw_front', models.CharField(max_length=200, verbose_name='\u6536\u5165\u65b0\u7f51\u91d1\u989d')),
                ('jhj_app_front', models.CharField(max_length=200, verbose_name='jhj\u91d1\u989d')),
                ('nm_app_front', models.CharField(max_length=200, verbose_name='\u5357\u95e8\u91d1\u989d')),
                ('guarantee_app_front', models.CharField(max_length=200, verbose_name='\u62c5\u4fdd\u91d1\u989d')),
                ('income_app_front', models.CharField(max_length=200, verbose_name='\u6536\u5165\u91d1\u989d')),
                ('jhj_app_behind', models.CharField(max_length=200, verbose_name='jhj\u91d1\u989d')),
                ('jhj_xw_behind', models.CharField(max_length=200, verbose_name='jhj\u65b0\u7f51\u91d1\u989d')),
                ('nm_app_behind', models.CharField(max_length=200, verbose_name='\u5357\u95e8\u91d1\u989d')),
                ('nm_xw_behind', models.CharField(max_length=200, verbose_name='\u5357\u95e8\u65b0\u7f51\u91d1\u989d')),
                ('guarantee_app_behind', models.CharField(max_length=200, verbose_name='\u62c5\u4fdd\u91d1\u989d')),
                ('guarantee_xw_behind', models.CharField(max_length=200, verbose_name='\u62c5\u4fdd\u65b0\u7f51\u91d1\u989d')),
                ('income_app_behind', models.CharField(max_length=200, verbose_name='\u6536\u5165\u91d1\u989d')),
                ('income_xw_behind', models.CharField(max_length=200, verbose_name='\u6536\u5165\u65b0\u7f51\u91d1\u989d')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jhj_rePayMents.LoanInformation')),
            ],
        ),
    ]
